# Generated by Django 4.2.11 on 2025-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_campaign_id',
            field=models.CharField(blank=True, help_text='ID used by marketing / brand team', max_length=64, null=True, unique=True),
        ),
    ]
