# Generated by Django 4.2.11 on 2025-07-16 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign_management', '0003_campaign_brand_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_campaign_id',
            field=models.CharField(default=1, help_text='ID used by marketing / brand team', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignassignment',
            name='field_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments_campaign_mgmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
