# Generated by Django 4.2.11 on 2025-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0005_alter_campaign_brand_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_campaign_id',
            field=models.CharField(help_text='ID used by marketing / brand team', max_length=64, unique=True),
        ),
    ]
