# Generated by Django 4.2.11 on 2025-07-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0007_alter_campaign_brand_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='collaterals/')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaterals', to='campaign_management.campaign')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaterals', to='campaign_management.collateral')),
            ],
        ),
    ]
