# Generated by Django 4.2.11 on 2025-08-04 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0008_collateral_campaigncollateral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_number', models.CharField(help_text='Message number/identifier', max_length=10)),
                ('message_text', models.TextField(help_text='The actual message template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaign_management.campaign')),
            ],
            options={
                'ordering': ['message_number'],
                'unique_together': {('campaign', 'message_number')},
            },
        ),
    ]
