# Generated by Django 4.2.11 on 2025-08-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0009_campaignmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmessage',
            name='message_number',
            field=models.CharField(help_text='Message number/identifier (e.g., 459, 458, etc.)', max_length=10),
        ),
    ]
