# Generated by Django 5.2.5 on 2025-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0010_alter_campaignmessage_message_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/logos/brand/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/logos/company/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/contracts/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='incharge_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='incharge_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='incharge_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='items_per_clinic_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='num_doctors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='printing_excel',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/printing/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='printing_required',
            field=models.BooleanField(default=False),
        ),
    ]
