# Generated by Django 5.2.5 on 2025-11-08 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0011_campaign_brand_logo_campaign_company_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_campaign_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID used by marketing / brand team', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='campaignassignment',
            index=models.Index(fields=['campaign', 'field_rep'], name='campaign_ma_campaig_c8c8cc_idx'),
        ),
    ]
