# Generated by Django 5.2.5 on 2025-12-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0012_alter_campaign_brand_campaign_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignassignment',
            name='campaign_ma_campaig_c8c8cc_idx',
        ),
    ]
