# Generated by Django 4.2.11 on 2025-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100, unique=True)),
                ('key_value', models.TextField()),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'secrets',
                'managed': False,
            },
        ),
    ]
