# Generated by Django 4.2.11 on 2025-07-10 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='field_id',
            field=models.CharField(blank=True, help_text='Internal ID printed on rep badge/card', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 format preferred', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('field_rep', 'Field Rep'), ('admin', 'Admin')], default='field_rep', max_length=20),
        ),
    ]
