# Generated by Django 4.2.11 on 2025-08-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_add_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer_hash',
            field=models.BinaryField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password_hash',
            field=models.BinaryField(blank=True, max_length=60, null=True),
        ),
    ]
