# Generated by Django 4.2.11 on 2025-08-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_prefilleddoctor_securityquestion_usersecurityanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepLoginOTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='login_otp', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otp_hash', models.BinaryField(max_length=60)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'rep_login_otp',
            },
        ),
    ]
