# Generated by Django 4.2.11 on 2025-08-02 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_reploginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_login_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_audit_whatsapp',
                'ordering': ['-created_at'],
            },
        ),
    ]
