# Generated by Django 4.2.11 on 2025-08-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(max_length=20)),
                ('otp_hash', models.BinaryField(max_length=60)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_verification_otps', to='shortlink_management.shortlink')),
            ],
            options={
                'db_table': 'doctor_verification_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
