# Generated by Django 5.2.5 on 2026-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink_management', '0002_doctorverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
