# Generated by Django 4.2.11 on 2025-07-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0008_collateral_campaigncollateral'),
        ('collateral_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncollateral',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_campaign_collaterals', to='campaign_management.campaign'),
        ),
    ]
