# Generated by Django 5.2 on 2025-04-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collateral_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaterals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigncollateral',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaterals', to='collateral_management.collateral'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncollateral',
            unique_together={('campaign', 'collateral')},
        ),
    ]
