# Generated by Django 4.2.11 on 2025-08-07 12:28

import collateral_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0010_alter_campaignmessage_message_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collateral_management', '0002_alter_campaigncollateral_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collateral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaigncollateral',
            name='collateral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaterals', to='collateral_management.collateral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='banner_1',
            field=models.ImageField(blank=True, null=True, upload_to=collateral_management.models.collateral_upload_path),
        ),
        migrations.AddField(
            model_name='collateral',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to=collateral_management.models.collateral_upload_path),
        ),
        migrations.AddField(
            model_name='collateral',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='campaign_management.campaign'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaterals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collateral',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collateral',
            name='purpose',
            field=models.CharField(choices=[('Doctor education short', 'Doctor education short'), ('Doctor education long', 'Doctor education long'), ('Patient education compliance', 'Patient education compliance'), ('Patient education general', 'Patient education general')], default='Doctor education short', max_length=50),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncollateral',
            unique_together={('campaign', 'collateral')},
        ),
    ]
