# Generated by Django 5.2.5 on 2025-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0003_alter_collateral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collateral',
            name='webinar_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='webinar_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='webinar_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collateral',
            name='webinar_url',
            field=models.URLField(blank=True),
        ),
    ]
