# Generated by Django 5.2.5 on 2025-12-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0004_collateral_doctor_name_collateral_webinar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('pdf_video', 'PDF + Video')], max_length=10),
        ),
    ]
