# Generated by Django 5.2.5 on 2026-01-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0013_remove_campaignassignment_campaign_ma_campaig_c8c8cc_idx'),
        ('collateral_management', '0005_alter_collateral_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Custom WhatsApp message for this collateral. Use $collateralLinks as placeholder for the actual link.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_messages', to='campaign_management.campaign')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_messages', to='collateral_management.collateral')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'collateral')},
            },
        ),
    ]
