# Generated by Django 4.2.11 on 2025-04-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRepCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reps', to='campaign_management.campaign')),
                ('field_rep', models.ForeignKey(limit_choices_to={'role': 'field_rep'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field-Rep Campaign',
                'verbose_name_plural': 'Field-Rep Campaigns',
                'unique_together': {('field_rep', 'campaign')},
            },
        ),
    ]
