--
-- Create model SourceMigrationBatchV2
--
CREATE TABLE `source_migration_batch_v2` (`migration_batch_id` varchar(64) NOT NULL PRIMARY KEY, `system_name` varchar(40) NOT NULL, `database_name` varchar(100) NOT NULL, `started_at` datetime(6) NOT NULL, `completed_at` datetime(6) NULL, `status` varchar(30) NOT NULL, `input_file_names` longtext NOT NULL, `created_by` varchar(120) NOT NULL, `notes` longtext NULL);
--
-- Create model MigrationExceptionV2
--
CREATE TABLE `migration_exception_v2` (`exception_id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `migration_batch_id` varchar(64) NOT NULL, `system_name` varchar(40) NOT NULL, `database_name` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `entity_type` varchar(40) NOT NULL, `issue_code` varchar(80) NOT NULL, `issue_details` longtext NOT NULL, `raw_payload_json` longtext NOT NULL, `resolution_status` varchar(30) NOT NULL, `resolved_by` varchar(120) NULL, `resolved_at` datetime(6) NULL, `resolution_notes` longtext NULL);
--
-- Create model InclinicFieldRepIdentityV2
--
CREATE TABLE `inclinic_field_rep_identity_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `inclinic_field_rep_identity_id` varchar(64) NOT NULL PRIMARY KEY, `field_rep_uuid` varchar(64) NULL, `campaign_fieldrep_id` varchar(255) NULL, `brand_supplied_field_rep_id` varchar(255) NULL, `source_column` varchar(120) NOT NULL, `source_value` varchar(255) NOT NULL, `source_value_normalized` varchar(255) NULL, `email_normalized` varchar(254) NULL, `phone_normalized` varchar(20) NULL, `match_basis` varchar(100) NOT NULL, `campaign_fieldrep_full_name` varchar(200) NULL, `campaign_fieldrep_phone_number` varchar(50) NULL, `campaign_fieldrep_is_active` bool NULL, `campaign_fieldrep_password_hash` varchar(128) NULL, `campaign_fieldrep_created_at` datetime(6) NULL, `campaign_fieldrep_updated_at` datetime(6) NULL, `campaign_fieldrep_brand_id` varchar(255) NULL, `campaign_fieldrep_user_id` varchar(255) NULL, `campaign_fieldrep_state` varchar(255) NULL, `user_management_user_id` varchar(255) NULL, `user_management_username` varchar(150) NULL, `user_management_first_name` varchar(150) NULL, `user_management_last_name` varchar(150) NULL, `user_management_email` varchar(254) NULL, `user_management_role` varchar(20) NULL, `user_management_field_id` varchar(50) NULL, `user_management_phone_number` varchar(15) NULL, `user_management_active` bool NULL, `user_management_is_active` bool NULL, `user_management_date_joined` datetime(6) NULL, `auth_user_id` varchar(255) NULL, `auth_user_username` varchar(150) NULL, `auth_user_first_name` varchar(150) NULL, `auth_user_last_name` varchar(150) NULL, `auth_user_email` varchar(254) NULL, `auth_user_is_active` bool NULL, `auth_user_date_joined` datetime(6) NULL);
--
-- Create model InclinicCampaignFieldRepAssignmentV2
--
CREATE TABLE `inclinic_campaign_field_rep_assignment_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `assignment_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NOT NULL, `legacy_campaign_id` varchar(255) NOT NULL, `legacy_campaign_id_normalized` varchar(255) NOT NULL, `field_rep_uuid` varchar(64) NOT NULL, `campaign_fieldrep_id` varchar(255) NOT NULL, `brand_supplied_field_rep_id` varchar(255) NULL, `assigned_at` datetime(6) NULL, `assigned_from` datetime(6) NULL, `assigned_to` datetime(6) NULL, `assignment_status` varchar(30) NOT NULL, `is_authoritative` bool NOT NULL, `old_state` varchar(255) NULL, `old_id` varchar(255) NULL, `old_field_rep_id` varchar(255) NULL, `old_created_at` datetime(6) NULL, `old_campaign_id` varchar(255) NULL);
--
-- Create model InclinicNonAuthoritativeAssignmentAuditV2
--
CREATE TABLE `inclinic_non_authoritative_assignment_audit_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `audit_uuid` varchar(64) NOT NULL PRIMARY KEY, `resolved_campaign_uuid` varchar(64) NULL, `resolved_field_rep_uuid` varchar(64) NULL, `matches_authoritative_campaign_campaignfieldrep` bool NOT NULL, `campaign_assignment_id` varchar(255) NULL, `campaign_assignment_assigned_on` datetime(6) NULL, `campaign_assignment_campaign_id` varchar(255) NULL, `campaign_assignment_field_rep_id` varchar(255) NULL, `admin_fieldrepcampaign_id` varchar(255) NULL, `admin_fieldrepcampaign_assigned_at` datetime(6) NULL, `admin_fieldrepcampaign_campaign_id` varchar(255) NULL, `admin_fieldrepcampaign_field_rep_id` varchar(255) NULL, `admin_fieldrepcampaign_uid` varchar(64) NULL);
--
-- Create model InclinicLegacyDoctorRepAliasV2
--
CREATE TABLE `inclinic_legacy_doctor_rep_alias_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `legacy_alias_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NOT NULL, `legacy_campaign_id` varchar(255) NOT NULL, `brand_supplied_field_rep_id` varchar(255) NOT NULL, `field_rep_name` varchar(255) NOT NULL, `campaign_fieldrep_id` varchar(255) NOT NULL, `field_rep_uuid` varchar(64) NOT NULL, `legacy_table` varchar(120) NOT NULL, `legacy_column` varchar(120) NOT NULL, `legacy_value` varchar(255) NOT NULL, `usage_scope` varchar(80) NOT NULL, `mapping_source` varchar(120) NOT NULL);
--
-- Create model InclinicDoctorV2
--
CREATE TABLE `inclinic_doctor_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `inclinic_doctor_uuid` varchar(64) NOT NULL PRIMARY KEY, `doctor_uuid` varchar(64) NULL, `display_name` varchar(255) NULL, `name_normalized` varchar(255) NULL, `phone_raw` varchar(50) NULL, `phone_normalized` varchar(20) NULL, `legacy_doctor_viewer_rep_id` varchar(255) NULL, `legacy_rep_alias_uuid` varchar(64) NULL, `legacy_rep_alias_matched` bool NOT NULL, `old_id` varchar(255) NULL, `old_name` varchar(100) NULL, `old_phone` varchar(15) NULL, `old_rep_id` varchar(255) NULL, `old_source` varchar(10) NULL);
--
-- Create model InclinicManualRepDoctorCorrectionStagingV2
--
CREATE TABLE `inclinic_manual_rep_doctor_correction_staging_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `staging_uuid` varchar(64) NOT NULL PRIMARY KEY, `legacy_campaign_id` varchar(255) NOT NULL, `brand_supplied_field_rep_id` varchar(255) NOT NULL, `field_rep_name_raw` varchar(255) NULL, `doctor_name_raw` varchar(255) NULL, `doctor_phone_raw` varchar(50) NULL, `doctor_name_normalized` varchar(255) NULL, `doctor_phone_normalized` varchar(20) NULL, `parse_status` varchar(30) NOT NULL, `parse_notes` longtext NULL);
--
-- Create model InclinicAssignedDoctorRosterV2
--
CREATE TABLE `inclinic_assigned_doctor_roster_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `assigned_roster_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NOT NULL, `legacy_campaign_id` varchar(255) NOT NULL, `brand_supplied_field_rep_id` varchar(255) NOT NULL, `campaign_fieldrep_id` varchar(255) NOT NULL, `field_rep_uuid` varchar(64) NOT NULL, `doctor_uuid` varchar(64) NULL, `inclinic_doctor_uuid` varchar(64) NULL, `doctor_name_raw` varchar(255) NOT NULL, `doctor_name_normalized` varchar(255) NOT NULL, `doctor_phone_raw` varchar(50) NOT NULL, `doctor_phone_normalized` varchar(20) NOT NULL, `legacy_doctor_viewer_rep_id` varchar(255) NULL, `match_basis` varchar(100) NOT NULL, `match_status` varchar(30) NOT NULL, `assignment_status` varchar(30) NOT NULL);
--
-- Create model InclinicShareEventV2
--
CREATE TABLE `inclinic_share_event_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `share_event_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NULL, `legacy_campaign_id` varchar(255) NULL, `collateral_uuid` varchar(64) NULL, `doctor_uuid` varchar(64) NULL, `inclinic_doctor_uuid` varchar(64) NULL, `doctor_phone_normalized` varchar(20) NULL, `shared_by_field_rep_uuid` varchar(64) NULL, `campaign_fieldrep_id` varchar(255) NULL, `field_rep_email_normalized` varchar(254) NULL, `field_rep_email_matches_campaign_fieldrep` bool NULL, `share_channel_normalized` varchar(30) NULL, `shared_at` datetime(6) NULL, `old_id` varchar(255) NULL, `old_share_channel` varchar(32) NULL, `old_share_timestamp` datetime(6) NULL, `old_message_text` longtext NULL, `old_created_at` datetime(6) NULL, `old_updated_at` datetime(6) NULL, `old_short_link_id` varchar(255) NULL, `old_collateral_id` varchar(255) NULL, `old_doctor_identifier` varchar(255) NULL, `old_brand_campaign_id` varchar(255) NULL, `old_field_rep_email` varchar(254) NULL, `old_field_rep_id` varchar(255) NULL);
--
-- Create model InclinicCollateralTransactionV2
--
CREATE TABLE `inclinic_collateral_transaction_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `transaction_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NULL, `legacy_campaign_id` varchar(255) NULL, `collateral_uuid` varchar(64) NULL, `doctor_uuid` varchar(64) NULL, `inclinic_doctor_uuid` varchar(64) NULL, `doctor_phone_normalized` varchar(20) NULL, `field_rep_uuid_from_campaign_fieldrep_id` varchar(64) NULL, `field_rep_uuid_from_brand_supplied_id` varchar(64) NULL, `resolved_field_rep_uuid` varchar(64) NULL, `campaign_fieldrep_id` varchar(255) NULL, `brand_supplied_field_rep_id` varchar(255) NULL, `field_rep_identifier_consistency_status` varchar(40) NOT NULL, `field_rep_resolution_basis` varchar(100) NOT NULL, `activity_summary_status` varchar(30) NOT NULL, `old_id` varchar(255) NULL, `old_transaction_id` varchar(128) NULL, `old_brand_campaign_id` varchar(255) NULL, `old_field_rep_id` varchar(64) NULL, `old_field_rep_unique_id` varchar(64) NULL, `old_doctor_name` varchar(255) NULL, `old_doctor_number` varchar(64) NULL, `old_doctor_unique_id` varchar(64) NULL, `old_collateral_id` varchar(255) NULL, `old_transaction_date` datetime(6) NULL, `old_has_viewed` bool NULL, `old_downloaded_pdf` bool NULL, `old_pdf_completed` bool NULL, `old_video_view_lt_50` integer NULL, `old_video_view_gt_50` bool NULL, `old_video_completed` bool NULL, `old_pdf_total_pages` integer UNSIGNED NULL CHECK (`old_pdf_total_pages` >= 0), `old_last_video_percentage` integer UNSIGNED NULL CHECK (`old_last_video_percentage` >= 0), `old_pdf_last_page` integer UNSIGNED NULL CHECK (`old_pdf_last_page` >= 0), `old_doctor_viewer_engagement_id` varchar(255) NULL, `old_share_management_engagement_id` varchar(255) NULL, `old_video_tracking_last_event_id` varchar(255) NULL, `old_created_at` datetime(6) NULL, `old_updated_at` datetime(6) NULL, `old_sent_at` datetime(6) NULL, `old_viewed_at` datetime(6) NULL, `old_first_viewed_at` datetime(6) NULL, `old_viewed_last_page_at` datetime(6) NULL, `old_video_lt_50_at` datetime(6) NULL, `old_video_gt_50_at` datetime(6) NULL, `old_video_100_at` datetime(6) NULL, `old_last_viewed_at` datetime(6) NULL, `old_dv_engagement_id` varchar(255) NULL, `old_field_rep_email` varchar(254) NULL, `old_share_channel` varchar(32) NULL, `old_sm_engagement_id` varchar(64) NULL, `old_video_watch_percentage` integer UNSIGNED NULL CHECK (`old_video_watch_percentage` >= 0));
--
-- Create model InclinicDoctorActivityEventV2
--
CREATE TABLE `inclinic_doctor_activity_event_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `activity_event_uuid` varchar(64) NOT NULL PRIMARY KEY, `transaction_uuid` varchar(64) NOT NULL, `share_event_uuid` varchar(64) NULL, `doctor_uuid` varchar(64) NULL, `inclinic_doctor_uuid` varchar(64) NULL, `campaign_uuid` varchar(64) NULL, `collateral_uuid` varchar(64) NULL, `field_rep_uuid_for_activity` varchar(64) NULL, `activity_type` varchar(40) NOT NULL, `activity_at` datetime(6) NULL, `activity_value` varchar(255) NULL, `source_flag_column` varchar(120) NOT NULL);
--
-- Create model InclinicCollateralV2
--
CREATE TABLE `inclinic_collateral_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `collateral_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NULL, `content_type_normalized` varchar(40) NULL, `status` varchar(30) NULL, `old_id` varchar(255) NULL, `old_type` varchar(10) NULL, `old_title` varchar(255) NULL, `old_file` varchar(255) NULL, `old_vimeo_url` varchar(255) NULL, `old_content_id` varchar(100) NULL, `old_upload_date` datetime(6) NULL, `old_is_active` bool NULL, `old_created_at` datetime(6) NULL, `old_updated_at` datetime(6) NULL, `old_banner_1` varchar(255) NULL, `old_banner_2` varchar(255) NULL, `old_campaign_id` varchar(255) NULL, `old_created_by_id` varchar(255) NULL, `old_description` varchar(255) NULL, `old_purpose` varchar(50) NULL, `old_doctor_name` varchar(255) NULL, `old_webinar_date` date NULL, `old_webinar_description` longtext NULL, `old_webinar_title` varchar(255) NULL, `old_webinar_url` varchar(255) NULL);
--
-- Create model InclinicCampaignCollateralV2
--
CREATE TABLE `inclinic_campaign_collateral_v2` (`source_system` varchar(40) NOT NULL, `source_database` varchar(100) NOT NULL, `source_table` varchar(120) NOT NULL, `source_pk_column` varchar(120) NOT NULL, `source_pk_value` varchar(255) NOT NULL, `source_created_at` datetime(6) NULL, `source_updated_at` datetime(6) NULL, `migration_batch_id` varchar(64) NOT NULL, `migrated_at` datetime(6) NOT NULL, `verification_status` varchar(30) NOT NULL, `verification_basis` varchar(100) NOT NULL, `is_current` bool NOT NULL, `valid_from` datetime(6) NULL, `valid_to` datetime(6) NULL, `raw_payload_json` longtext NOT NULL, `campaign_collateral_uuid` varchar(64) NOT NULL PRIMARY KEY, `campaign_uuid` varchar(64) NULL, `collateral_uuid` varchar(64) NOT NULL, `old_id` varchar(255) NULL, `old_start_date` datetime(6) NULL, `old_end_date` datetime(6) NULL, `old_created_at` datetime(6) NULL, `old_updated_at` datetime(6) NULL, `old_campaign_id` varchar(255) NULL, `old_collateral_id` varchar(255) NULL);
CREATE INDEX `migration_e_migrati_af6968_idx` ON `migration_exception_v2` (`migration_batch_id`, `issue_code`);
CREATE INDEX `migration_e_source__d3f3bf_idx` ON `migration_exception_v2` (`source_table`, `source_pk_value`);
CREATE INDEX `inclinic_field_rep_identity_v2_field_rep_uuid_3ed24f2e` ON `inclinic_field_rep_identity_v2` (`field_rep_uuid`);
CREATE INDEX `inclinic_field_rep_identity_v2_campaign_fieldrep_id_21ec2ef6` ON `inclinic_field_rep_identity_v2` (`campaign_fieldrep_id`);
CREATE INDEX `inclinic_field_rep_identity_brand_supplied_field_rep_id_3165af0c` ON `inclinic_field_rep_identity_v2` (`brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_fi_source__aa083c_idx` ON `inclinic_field_rep_identity_v2` (`source_table`, `source_column`, `source_value`);
CREATE INDEX `inclinic_fi_campaig_654073_idx` ON `inclinic_field_rep_identity_v2` (`campaign_fieldrep_id`, `brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_campaign_field_rep_legacy_campaign_id_d2ae52b3` ON `inclinic_campaign_field_rep_assignment_v2` (`legacy_campaign_id`);
CREATE INDEX `inclinic_campaign_field_rep_legacy_campaign_id_normaliz_5219a49d` ON `inclinic_campaign_field_rep_assignment_v2` (`legacy_campaign_id_normalized`);
CREATE INDEX `inclinic_campaign_field_rep_field_rep_uuid_cdb3a206` ON `inclinic_campaign_field_rep_assignment_v2` (`field_rep_uuid`);
CREATE INDEX `inclinic_campaign_field_rep_campaign_fieldrep_id_5868e5a9` ON `inclinic_campaign_field_rep_assignment_v2` (`campaign_fieldrep_id`);
CREATE INDEX `inclinic_ca_legacy__6de9a4_idx` ON `inclinic_campaign_field_rep_assignment_v2` (`legacy_campaign_id_normalized`, `campaign_fieldrep_id`);
CREATE INDEX `inclinic_ca_campaig_35adfc_idx` ON `inclinic_campaign_field_rep_assignment_v2` (`campaign_uuid`, `field_rep_uuid`);
CREATE INDEX `inclinic_no_source__6fea1d_idx` ON `inclinic_non_authoritative_assignment_audit_v2` (`source_table`, `source_pk_value`);
CREATE INDEX `inclinic_legacy_doctor_rep_alias_v2_campaign_uuid_7806fcaa` ON `inclinic_legacy_doctor_rep_alias_v2` (`campaign_uuid`);
CREATE INDEX `inclinic_legacy_doctor_rep_alias_v2_legacy_campaign_id_b027b190` ON `inclinic_legacy_doctor_rep_alias_v2` (`legacy_campaign_id`);
CREATE INDEX `inclinic_legacy_doctor_rep__brand_supplied_field_rep_id_996f667c` ON `inclinic_legacy_doctor_rep_alias_v2` (`brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_legacy_doctor_rep__campaign_fieldrep_id_e66c3505` ON `inclinic_legacy_doctor_rep_alias_v2` (`campaign_fieldrep_id`);
CREATE INDEX `inclinic_legacy_doctor_rep_alias_v2_field_rep_uuid_6611f7f3` ON `inclinic_legacy_doctor_rep_alias_v2` (`field_rep_uuid`);
CREATE INDEX `inclinic_legacy_doctor_rep_alias_v2_legacy_value_4a153082` ON `inclinic_legacy_doctor_rep_alias_v2` (`legacy_value`);
CREATE INDEX `inclinic_le_legacy__1e270e_idx` ON `inclinic_legacy_doctor_rep_alias_v2` (`legacy_campaign_id`, `brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_le_legacy__734828_idx` ON `inclinic_legacy_doctor_rep_alias_v2` (`legacy_table`, `legacy_column`, `legacy_value`);
CREATE INDEX `inclinic_doctor_v2_doctor_uuid_9a2210f1` ON `inclinic_doctor_v2` (`doctor_uuid`);
CREATE INDEX `inclinic_doctor_v2_phone_normalized_5b15f1a1` ON `inclinic_doctor_v2` (`phone_normalized`);
CREATE INDEX `inclinic_doctor_v2_legacy_doctor_viewer_rep_id_6bfa3412` ON `inclinic_doctor_v2` (`legacy_doctor_viewer_rep_id`);
CREATE INDEX `inclinic_do_phone_n_36588b_idx` ON `inclinic_doctor_v2` (`phone_normalized`);
CREATE INDEX `inclinic_do_legacy__71e2f1_idx` ON `inclinic_doctor_v2` (`legacy_doctor_viewer_rep_id`, `phone_normalized`);
CREATE INDEX `inclinic_manual_rep_doctor__legacy_campaign_id_8a335b46` ON `inclinic_manual_rep_doctor_correction_staging_v2` (`legacy_campaign_id`);
CREATE INDEX `inclinic_manual_rep_doctor__brand_supplied_field_rep_id_6196f5ab` ON `inclinic_manual_rep_doctor_correction_staging_v2` (`brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_ma_legacy__ce56d1_idx` ON `inclinic_manual_rep_doctor_correction_staging_v2` (`legacy_campaign_id`, `brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_assigned_doctor_roster_v2_campaign_uuid_064b8116` ON `inclinic_assigned_doctor_roster_v2` (`campaign_uuid`);
CREATE INDEX `inclinic_assigned_doctor_roster_v2_legacy_campaign_id_79e3c060` ON `inclinic_assigned_doctor_roster_v2` (`legacy_campaign_id`);
CREATE INDEX `inclinic_assigned_doctor_ro_brand_supplied_field_rep_id_0f3f0497` ON `inclinic_assigned_doctor_roster_v2` (`brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_assigned_doctor_roster_v2_campaign_fieldrep_id_f5d56d7a` ON `inclinic_assigned_doctor_roster_v2` (`campaign_fieldrep_id`);
CREATE INDEX `inclinic_assigned_doctor_roster_v2_field_rep_uuid_fe0a0809` ON `inclinic_assigned_doctor_roster_v2` (`field_rep_uuid`);
CREATE INDEX `inclinic_assigned_doctor_ro_doctor_phone_normalized_435dacca` ON `inclinic_assigned_doctor_roster_v2` (`doctor_phone_normalized`);
CREATE INDEX `inclinic_as_campaig_625259_idx` ON `inclinic_assigned_doctor_roster_v2` (`campaign_uuid`, `field_rep_uuid`, `doctor_phone_normalized`);
CREATE INDEX `inclinic_as_legacy__74c7a0_idx` ON `inclinic_assigned_doctor_roster_v2` (`legacy_campaign_id`, `brand_supplied_field_rep_id`);
CREATE INDEX `inclinic_share_event_v2_campaign_uuid_421bdefb` ON `inclinic_share_event_v2` (`campaign_uuid`);
CREATE INDEX `inclinic_share_event_v2_doctor_phone_normalized_4939114c` ON `inclinic_share_event_v2` (`doctor_phone_normalized`);
CREATE INDEX `inclinic_share_event_v2_shared_by_field_rep_uuid_10108977` ON `inclinic_share_event_v2` (`shared_by_field_rep_uuid`);
CREATE INDEX `inclinic_sh_campaig_0a204a_idx` ON `inclinic_share_event_v2` (`campaign_uuid`, `shared_by_field_rep_uuid`);
CREATE INDEX `inclinic_sh_doctor__d00fff_idx` ON `inclinic_share_event_v2` (`doctor_phone_normalized`, `old_collateral_id`);
CREATE INDEX `inclinic_collateral_transaction_v2_campaign_uuid_56df659b` ON `inclinic_collateral_transaction_v2` (`campaign_uuid`);
CREATE INDEX `inclinic_collateral_transac_doctor_phone_normalized_ff0a5f04` ON `inclinic_collateral_transaction_v2` (`doctor_phone_normalized`);
CREATE INDEX `inclinic_collateral_transac_resolved_field_rep_uuid_902595a8` ON `inclinic_collateral_transaction_v2` (`resolved_field_rep_uuid`);
CREATE INDEX `inclinic_co_campaig_0da81a_idx` ON `inclinic_collateral_transaction_v2` (`campaign_uuid`, `resolved_field_rep_uuid`);
CREATE INDEX `inclinic_co_doctor__2bad64_idx` ON `inclinic_collateral_transaction_v2` (`doctor_phone_normalized`, `old_collateral_id`);
CREATE INDEX `inclinic_co_field_r_ae1860_idx` ON `inclinic_collateral_transaction_v2` (`field_rep_identifier_consistency_status`);
CREATE INDEX `inclinic_doctor_activity_event_v2_transaction_uuid_cee9f6a0` ON `inclinic_doctor_activity_event_v2` (`transaction_uuid`);
CREATE INDEX `inclinic_doctor_activity_event_v2_activity_type_377f1cad` ON `inclinic_doctor_activity_event_v2` (`activity_type`);
CREATE INDEX `inclinic_do_campaig_de0e07_idx` ON `inclinic_doctor_activity_event_v2` (`campaign_uuid`, `field_rep_uuid_for_activity`, `activity_type`);
CREATE INDEX `inclinic_do_doctor__ffe382_idx` ON `inclinic_doctor_activity_event_v2` (`doctor_uuid`, `activity_type`);
CREATE INDEX `inclinic_co_old_id_c513e3_idx` ON `inclinic_collateral_v2` (`old_id`);
CREATE INDEX `inclinic_ca_campaig_7becc1_idx` ON `inclinic_campaign_collateral_v2` (`campaign_uuid`, `collateral_uuid`);
CREATE INDEX `inclinic_ca_old_cam_cf757b_idx` ON `inclinic_campaign_collateral_v2` (`old_campaign_id`, `old_collateral_id`);
