# Generated by Django 5.2 on 2025-04-17 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortlink_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_completed', models.BooleanField(default=False)),
                ('last_page_scrolled', models.IntegerField(default=0)),
                ('video_watch_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='shortlink_management.shortlink')),
            ],
        ),
    ]
