# Generated by Django 4.2.11 on 2025-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_viewer', '0002_add_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorengagement',
            name='status',
        ),
    ]
