# Generated by Django 4.2.11 on 2025-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_viewer', '0003_remove_doctorengagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorengagement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not-started'), (1, 'in-progress'), (2, 'completed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctorengagement',
            name='last_page_scrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorengagement',
            name='video_watch_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
