# Generated by Django 4.2.11 on 2025-07-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0001_initial'),
        ('doctor_viewer', '0006_alter_doctor_name_alter_doctor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='collateral_management.collateral')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_links', to='doctor_viewer.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'collateral')},
            },
        ),
    ]
