# Generated by Django 4.2.11 on 2025-08-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_viewer', '0007_doctorcollateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('prefill', 'Pre-filled')], default='manual', help_text='Source of the doctor record', max_length=10),
        ),
    ]
