FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/admin-console/package*.json ./
RUN npm ci
COPY frontend/admin-console .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist .
RUN npm i -g serve
CMD ["serve", "-s", ".", "--single"]