# Generated by Django 5.2 on 2025-04-16 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortlink_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_identifier', models.CharField(max_length=255)),
                ('share_channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email')], default='WhatsApp', max_length=50)),
                ('share_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to=settings.AUTH_USER_MODEL)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='shortlink_management.shortlink')),
            ],
        ),
    ]
