# Generated by Django 4.2.11 on 2025-07-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0001_initial'),
        ('sharing_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelog',
            name='collateral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='collateral_management.collateral'),
            preserve_default=False,
        ),
    ]
