# Generated by Django 4.2.11 on 2025-07-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0001_initial'),
        ('sharing_management', '0002_sharelog_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelog',
            name='collateral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_logs', to='collateral_management.collateral'),
        ),
    ]
