# Generated by Django 4.2.11 on 2025-07-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0002_alter_campaigncollateral_campaign'),
        ('sharing_management', '0003_alter_sharelog_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelog',
            name='collateral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='collateral_management.collateral'),
            preserve_default=False,
        ),
    ]
