# Generated by Django 4.2.11 on 2025-07-31 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink_management', '0001_initial'),
        ('sharing_management', '0004_alter_sharelog_collateral'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_method', models.CharField(choices=[('email', 'Email ID'), ('gmail', 'Gmail ID'), ('whatsapp', 'WhatsApp Number')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sharelog',
            name='doctor_identifier',
        ),
        migrations.CreateModel(
            name='DoctorEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_whatsapp', models.CharField(max_length=15)),
                ('verification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_timestamp', models.DateTimeField(blank=True, null=True)),
                ('download_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='shortlink_management.shortlink')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('is_prefilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='sharing_management.fieldrepresentative')),
            ],
        ),
        migrations.AddField(
            model_name='sharelog',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='sharing_management.doctor'),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='field_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='sharing_management.fieldrepresentative'),
        ),
    ]
