# Generated by Django 4.2.11 on 2025-07-31 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing_management', '0005_fieldrepresentative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelog',
            name='doctor',
        ),
        migrations.AddField(
            model_name='sharelog',
            name='doctor_identifier',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='field_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
