# Generated by Django 4.2.11 on 2025-08-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_management', '0006_remove_sharelog_doctor_sharelog_doctor_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorengagement',
            name='short_link',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='field_id',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='password',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorEngagement',
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing_management.securityquestion'),
        ),
    ]
