# Generated by Django 4.2.11 on 2025-08-02 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_management', '0007_securityquestion_remove_doctorengagement_short_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrepresentative',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email ID'), ('gmail', 'Gmail ID'), ('whatsapp', 'WhatsApp Number')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='field_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
