# Generated by Django 4.2.11 on 2025-08-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_management', '0008_fieldrepresentative_auth_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('video_status', models.PositiveSmallIntegerField()),
                ('video_percentage', models.CharField(max_length=10)),
                ('comment', models.CharField(default='Video Viewed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_logs', to='sharing_management.sharelog')),
            ],
            options={
                'unique_together': {('share_log', 'user_id', 'video_percentage')},
            },
        ),
    ]
