# Generated by Django 5.2.5 on 2025-11-25 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_management', '0009_videotrackinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=128)),
                ('brand_campaign_id', models.CharField(db_index=True, max_length=64)),
                ('field_rep_id', models.CharField(db_index=True, max_length=64)),
                ('field_rep_unique_id', models.CharField(blank=True, max_length=64, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_number', models.CharField(db_index=True, max_length=15)),
                ('doctor_unique_id', models.CharField(blank=True, max_length=64, null=True)),
                ('collateral_id', models.BigIntegerField(db_index=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('has_viewed', models.BooleanField(default=False)),
                ('has_downloaded_pdf', models.BooleanField(default=False)),
                ('has_viewed_last_page', models.BooleanField(default=False)),
                ('video_view_lt_50', models.BooleanField(default=False)),
                ('video_view_gt_50', models.BooleanField(default=False)),
                ('video_view_100', models.BooleanField(default=False)),
                ('total_video_events', models.PositiveIntegerField(default=0)),
                ('last_video_percentage', models.PositiveSmallIntegerField(default=0)),
                ('last_page_scrolled', models.PositiveIntegerField(default=0)),
                ('doctor_viewer_engagement_id', models.BigIntegerField(blank=True, null=True)),
                ('share_management_engagement_id', models.BigIntegerField(blank=True, null=True)),
                ('video_tracking_last_event_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_pdf_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_last_page_at', models.DateTimeField(blank=True, null=True)),
                ('video_lt_50_at', models.DateTimeField(blank=True, null=True)),
                ('video_gt_50_at', models.DateTimeField(blank=True, null=True)),
                ('video_100_at', models.DateTimeField(blank=True, null=True)),
                ('last_video_event_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['brand_campaign_id', 'transaction_date'], name='sharing_man_brand_c_5e27b0_idx'), models.Index(fields=['doctor_number', 'collateral_id'], name='sharing_man_doctor__aeac9e_idx')],
                'unique_together': {('field_rep_id', 'doctor_number', 'collateral_id', 'transaction_date')},
            },
        ),
    ]
