# Generated by Django 4.2.11 on 2026-06-03 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_management', '0007_collateralmessage_reminder_message'),
        ('shortlink_management', '0003_shortlink_click_count'),
        ('sharing_management', '0011_repair_collateraltransaction_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRepSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_field_rep_id', models.BigIntegerField(db_index=True, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('security_answer_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sharing_management_fieldrepsecurityprofile',
            },
        ),
        migrations.RemoveField(
            model_name='fieldrepresentative',
            name='security_question',
        ),
        migrations.AlterModelOptions(
            name='securityquestion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sharelog',
            options={'ordering': ['-share_timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='videotrackinglog',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sharelog',
            name='field_rep',
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sharelog',
            name='brand_campaign_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sharelog',
            name='field_rep_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sharelog',
            name='field_rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='collateral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_logs', to='collateral_management.collateral'),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='doctor_identifier',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='share_channel',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='share_timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='short_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_logs', to='shortlink_management.shortlink'),
        ),
        migrations.AlterField(
            model_name='videotrackinglog',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videotrackinglog',
            name='user_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='videotrackinglog',
            name='video_percentage',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='videotrackinglog',
            name='video_status',
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['field_rep_id', 'share_timestamp'], name='sharing_man_field_r_f4fe36_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['doctor_identifier', 'share_timestamp'], name='sharing_man_doctor__894603_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['collateral', 'share_timestamp'], name='sharing_man_collate_fc8883_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['brand_campaign_id', 'share_timestamp'], name='sharing_man_brand_c_824b68_idx'),
        ),
        migrations.AddIndex(
            model_name='videotrackinglog',
            index=models.Index(fields=['share_log', 'user_id'], name='sharing_man_share_l_b69892_idx'),
        ),
        migrations.AlterModelTable(
            name='collateraltransaction',
            table='sharing_management_collateraltransaction',
        ),
        migrations.AlterModelTable(
            name='securityquestion',
            table='sharing_management_securityquestion',
        ),
        migrations.AlterModelTable(
            name='sharelog',
            table='sharing_management_sharelog',
        ),
        migrations.AlterModelTable(
            name='videotrackinglog',
            table='sharing_management_videotrackinglog',
        ),
        migrations.DeleteModel(
            name='FieldRepresentative',
        ),
        migrations.AddField(
            model_name='fieldrepsecurityprofile',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldrep_profiles', to='sharing_management.securityquestion'),
        ),
    ]
